// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgKgH2oPMytyy6E-aBJBeE6ucYa7dR3Oo',
    appId: '1:1052449748540:web:e06ecd8b606de667b3b539',
    messagingSenderId: '1052449748540',
    projectId: 'aplikasibengkel-36c8b',
    authDomain: 'aplikasibengkel-36c8b.firebaseapp.com',
    storageBucket: 'aplikasibengkel-36c8b.appspot.com',
    measurementId: 'G-KRS2BB8HRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ50wJvv2iIsZzjTmYRagb8cWBBMty92c',
    appId: '1:1052449748540:android:0091168d9df9532eb3b539',
    messagingSenderId: '1052449748540',
    projectId: 'aplikasibengkel-36c8b',
    storageBucket: 'aplikasibengkel-36c8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANZoMAfBWX2DM6gYej6uZlqByqBmND3r4',
    appId: '1:1052449748540:ios:c09efbde32d434c1b3b539',
    messagingSenderId: '1052449748540',
    projectId: 'aplikasibengkel-36c8b',
    storageBucket: 'aplikasibengkel-36c8b.appspot.com',
    iosClientId: '1052449748540-r4gt8b56lec6n15hma79d8k9a65e58b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiBengkelsehat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANZoMAfBWX2DM6gYej6uZlqByqBmND3r4',
    appId: '1:1052449748540:ios:c09efbde32d434c1b3b539',
    messagingSenderId: '1052449748540',
    projectId: 'aplikasibengkel-36c8b',
    storageBucket: 'aplikasibengkel-36c8b.appspot.com',
    iosClientId: '1052449748540-r4gt8b56lec6n15hma79d8k9a65e58b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiBengkelsehat',
  );
}
